version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: autocurator
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: autocurator_db
    volumes:
    - postgres-data:/var/lib/postgressql/data
    ports:
    - "5432:5432"

  backend:
    build: ./apps/backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./apps/backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://autocurator:devpassword@db:5432/autocurator_db

  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend:/app/apps/frontend
    depends_on:
      - backend


volumes:
  postgres-data: {}